POST http://localhost:3003/api/user/sign-in
Content-Type: application/json

{
    "name":"test",
    "email" : "Test43@gmail.com",
    "password": "test123",
    "confirmPassword": "test123",
    "phone":"0323235"
}